### ISSUE TITLE
CI - Error: Failed running "src.hook": "npm run build" due to the following error: Command failed: npm run build

### ISSUE THREAD

**Issue by josoroma** [serverless-components/website#73]
Hi!

I am hitting this error on app.serverless.com (ci/cd deploys):

```
Error: Failed running "src.hook": "npm run build" due to the following error: Command failed: npm run build
```

## Using Create React App with TypeScript (`"react": "^17.0.1"` && `"typescript": "^4.0.3",`):

```
org: usernameorg
app: app
component: website
name: app
#
stage: ${env:AWS_STAGE}
#
# https://github.com/serverless/components#simplicity
#
inputs:
  name: app-${stage}
  region: ${env:AWS_REGION}
  src:
    src: ./src
    hook: npm run build
    dist: ./build
```

##

```
  "scripts": {
    ...
    "build": "react-scripts build",
    "deploy:development": "export AWS_STAGE='development' && export AWS_REGION='us-west-2' && sls deploy",
    "remove:development": "export AWS_STAGE='development' && export AWS_REGION='us-west-2' && sls remove",
    ...
  },
```

## app.serverless.com (ci/cd deploys) error

```
Build step: serverless deploy --stage development --region us-west-2 --force --org usernameorg --app app --debug
Initializing...
Action: "deploy" - Stage: "development" - Org: "usernameorg" - App: "app" - Name: "app"
Deploying...
 Error: Failed running "src.hook": "npm run build" due to the following error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clientapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clientapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-20T00_31_11_903Z-debug.log
    at exec (/var/lang/lib/node_modules/serverless/node_modules/@serverless/platform-client/src/instance.js:200:13)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
6s › Serverless › Failed running "src.hook": "npm run build" due to the following error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clientapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clientapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-20T00_31_11_903Z-debug.log
 
  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 
Build step failed: serverless deploy --stage development --region us-west-2 --force --org usernameorg --app app --debug
Deploy failed!
Error: Build step failed: serverless deploy --stage development --region us-west-2 --force --org usernameorg --app app --debug
```

**Comment by BenjaminG** [comment]
Same here, any way to get the content of the `/root/.npm/_logs/*******-debug.log` file ?

**Comment by darbio** [comment]
Same here...

**Comment by darbio** [comment]
For me, the problem was that I had some warnings when I built the project in a CI environment (when `CI=true`). When CI is set, react-scripts build will treat warnings as errors and the build will fail.

You can set your build script to `CI= react-scripts build` if you want to trick the build scripts.

**Comment by BenjaminG** [comment]
@darbio thanks for your suggestion, I fixed all the warning I had coming from Eslint so that it can build even with CI=true.

But I still have the same issue by pushing my code on Github.
Locally this works :  CI=true serverless deploy --stage staging --force --org b***** --app fmg --debug

**Comment by josoroma-zz** [comment]
Thank you!

Buut no luck from my side:

![image](https://user-images.githubusercontent.com/69951/108915513-98bd2480-75f2-11eb-8ece-912dbd76750d.png)

```
CI=true serverless deploy --aws-profile xyz --stage dev --force --org abc--app abc-app-website --debu
```

![image](https://user-images.githubusercontent.com/69951/108915591-b8ece380-75f2-11eb-8ddf-655a184ebdb3.png)

**Comment by PGuimarais** [comment]
also running into this issue, can't seem to find a work around other than manually deploying

**Comment by andrescabana86** [comment]
Me too. Could you please @PGuimarais tell me how to deploy manually b/c I'm new on this

**Comment by darbio** [comment]
> Me too. Could you please @PGuimarais tell me how to deploy manually b/c I'm new on this

Just run the `deploy` command from terminal.

**Comment by vtr-rivia** [comment]
Up. Same problem here
`
npm ERR!     /root/.npm/_logs/2021-09-24T14_13_03_998Z-debug.log
    at /var/lang/lib/node_modules/serverless/node_modules/@serverless/platform-client/src/instance.js:200:13
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
20s › Serverless › Failed running "src.hook": "npm run build" due to the following error: Command failed: npm run build
`
