### ISSUE TITLE
TypeError: Cannot read property 'ping' of null

### ISSUE THREAD

**Issue by darbio** [serverless-components/website#78]
I don't know if this is the right place for this - the error looks like it's in platform-client - but that is a private repo.

I get this intermittent error when I deploy from CI/CD environment:

```
Build step: serverless deploy --stage dev --region us-east-1 --force --org darbio --app tsz-next --debug
Initializing...
Action: "deploy" - Stage: "dev" - Org: "darbio" - App: "tsz-next" - Name: "frontend"
Deploying...
/var/lang/lib/node_modules/serverless/node_modules/@serverless/platform-client/src/Connection.js:114
            this.connection.ping();
                            ^
TypeError: Cannot read property 'ping' of null
    at Timeout.pingInterval.setInterval [as _onTimeout] (/var/lang/lib/node_modules/serverless/node_modules/@serverless/platform-client/src/Connection.js:114:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Build step failed: serverless deploy --stage dev --region us-east-1 --force --org darbio --app tsz-next --debug
```

I think there is a bug in platform-client when the connection times out.

**Comment by darbio** [comment]
Bump. I'm still getting this. Anyone have any pointers?

**Comment by EyeDreamt** [comment]
I also have this same issue.
